### ISSUE TITLE
avworker is returning an error

### ISSUE THREAD

**Issue by gipsh** [4clouds/yi-stream#1]
Hi, 
Im trying to run your binary in another camera built on the hi3518 . 
The avworker is returning this: 

```
[flv @ 0x1b970e0] Application provided invalid, non monotonically increasing dts to muxer in stream 0: 240 >= 40
Error muxing packet
[flv @ 0x1b970e0] Failed to update header with correct duration.
[flv @ 0x1b970e0] Failed to update header with correct filesize.
# SIOCGMIIPHY on 'eth0' failed
```

Also, why did you use your own rtsp server and not the one provided by the camera ? 

Thanks

**Comment by wregen** [comment]
Hi,
avworker-min is basically ffmpeg binary with simplified parameters. I suggest you compile ffmpeg for hi3518, and issue the following command:

ffmpeg -i rtsp://localhost/stream_name -acodec copy -vcodec copu -f flv rtmp://server/stream-name.

With this you will have better debugging options.

To answer your question about custom rtsp server. YI does not have rtsp server. The rtspsvr binary is (probably) prepared by a gay called mp77v (who is very active on http://4pda.ru/forum. I too the binary from http://xiaoyi.querex.be/.

I hope this will help you.

Thanks.

**Comment by gipsh** [comment]
Thanks, i will try ffmpeg on my  camera. 

Do you have the compilation parameters? i'm amazed of how small you binary is. 

It seems the YI audio codec is mp3 or ACC as you are copying the stream directly.

**Comment by wregen** [comment]
Hi,
Below are ffmpeg configure options:

```
./configure \
--enable-cross-compile \
--cross-prefix=/opt/hisi-linux-nptl/arm-hisiv100-linux/bin/arm-hisiv100-linux-uclibcgnueabi- \
--enable-gpl \
--arch=armv5te \
--enable-armv5te \
--target-os=linux \
--enable-gpl \
--disable-doc \
--disable-asm \
--disable-debug \
--disable-filters \
--disable-ffplay \
--disable-ffserver \
--disable-encoders \
--disable-decoders \
--disable-protocols \
--disable-muxers \
--disable-demuxers \
--disable-outdevs \
--enable-encoder=flv \
--enable-decoder=flv \
--enable-muxer=flv,rtsp,mpegts,h264 \
--enable-demuxer=flv,rtsp,mpegts,h264 \
--enable-protocol=rtmp,rtp,udp,file,tcp \
--disable-parsers \
--enable-parser=aac,aac_latm,h264 \
--disable-bsfs \
--enable-bsf=aac_adtstoasc,h264_mp4toannexb \
--disable-debug \
--enable-small 
```

Disabling almost all ffmped features makes the binary small. Also I am using http://upx.sourceforge.net/ to make it even smaller.

And yes, YI stream is h.264 video and aac audio, thus it is easy to push the stream to Youtube.

**Comment by wregen** [comment]
One more thing. In order to compile ffmpeg for the arm you need to comment the line with 

```
check_ldflags -Wl,-z,noexecstack
```

in configure script.

**Comment by gipsh** [comment]
Thanks !!
Really appreciate it.
